
export const GOALS_URL ="/goals"
export const DEPARTMENTS_URL = "/departments"
export const EMPLOYEES_GOALS_URL = "/employee-goals"
export const EMPLOYEES_URL = "/users"
export const DEPARTMENT_GOAL_ASSESSMENT_URL ="/deparment-goal-assessments"
export const LOGIN_URL ="/login"
export const SIGNUP_URL ="/register"
export const VERIFYEMAIL_URL ="/confirm-email"
export const PERFORMANCE_MATRIX_CHART_URL = "/department-performance"
export const GENERAL_PERFORMANCE_CHART_URL = "/department-performance/overall-average"
export const ORGANIZATIONAL_CHART_URL = "/department-performance/get-monthly-average-performance"
export const GOAL_COUNT_URL = "/goals/goal-status-count"
export const CREATE_DEPRATMENT ="/departments"

