
export const GOALS_URL ="/goals"
export const MY_GOALS_URL ="/goals/my-assigned-goal"
export const UNACCESSED_GOALS_URL ="/goals/get-unassessed-goals"
export const DEPARTMENTS_URL = "/departments"
export const EMPLOYEES_GOALS_URL = "/employee-goals"
export const EMPLOYEES_URL = "/users"
export const GOAL_ASSESSMENT_URL ="/goal-assessments"
export const LOGIN_URL ="/login"
export const SIGNUP_URL ="/register"
export const VERIFYEMAIL_URL ="/confirm-email"
export const PERFORMANCE_MATRIX_CHART_URL = "/department-performance"
export const GENERAL_PERFORMANCE_CHART_URL = "/performance/overall-average"
export const ORGANIZATIONAL_AVERAGE_PER_MONTH_CHART_URL = "/performance/get-monthly-average-performance"
export const GOAL_COUNT_URL = "/performance/get-goal-ratings"
export const GOAL_STATUS_COUNT = "/goals/goal-status-count"
export const CREATE_DEPRATMENT ="/departments"
export const CREATE_EMPLOYEES_URL = "/add-member"
export const RESET_PASSWORD ="/reset-password"
export const REQUEST_RESET_PASSWORD ="/request-password-reset"
export const TOP_GOALS = "/goal-assessments/get-top-assessment"
export const UPDATE_GOAL_PROGRESS = "/goals/update-progress"
export const GOAL_CATEGORY_COUNT = "/goals/goal-type-count"
export const GOAL_BADGES = "/goal-assessments/get-ratings-summary"
export const GET_CATEGORY_ACHIEVED = "/performance/get-monthly-average-achieved-performance"
export const ACTION_ITEMS = "/goals/dept"
export const USER_RATING = "/users/update-rating" 
export const USER_RATING_BY_ID = "/goal-assessments/get-employee-summary" 
export const USER_BADGES_TABLE = "/goal-assessments/get-all-users-badge"


